#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
补充中国城市的中文名称
基于拼音/英文名称手工整理的映射表
"""

# 中国城市名称映射表（拼音/英文 -> 中文）
CITY_NAME_MAPPING = {
    # 直辖市
    "Beijing": "北京",
    "Shanghai": "上海",
    "Tianjin": "天津",
    "Chongqing": "重庆",
    
    # 省会城市
    "Guangzhou": "广州",
    "Shenzhen": "深圳",
    "Chengdu": "成都",
    "Wuhan": "武汉",
    "Hangzhou": "杭州",
    "Nanjing": "南京",
    "Xi'an": "西安",
    "Shenyang": "沈阳",
    "Harbin": "哈尔滨",
    "Changchun": "长春",
    "Dalian": "大连",
    "Qingdao": "青岛",
    "Jinan": "济南",
    "Zhengzhou": "郑州",
    "Hefei": "合肥",
    "Changsha": "长沙",
    "Nanchang": "南昌",
    "Fuzhou": "福州",
    "Xiamen": "厦门",
    "Kunming": "昆明",
    "Guiyang": "贵阳",
    "Nanning": "南宁",
    "Haikou": "海口",
    "Sanya": "三亚",
    "Lhasa": "拉萨",
    "Lanzhou": "兰州",
    "Xining": "西宁",
    "Yinchuan": "银川",
    "Urumqi": "乌鲁木齐",
    "Hohhot": "呼和浩特",
    "Taiyuan": "太原",
    "Shijiazhuang": "石家庄",
    
    # 地级市（按省份整理）
    # 广东省
    "Bao'an": "宝安",
    "Dongguan": "东莞",
    "Foshan": "佛山",
    "Zhuhai": "珠海",
    "Zhongshan": "中山",
    "Jiangmen": "江门",
    "Huizhou": "惠州",
    "Shantou": "汕头",
    "Zhanjiang": "湛江",
    "Shaoguan": "韶关",
    "Meizhou": "梅州",
    "Qingyuan": "清远",
    "Yangjiang": "阳江",
    "Maoming": "茂名",
    "Chaozhou": "潮州",
    "Jieyang": "揭阳",
    "Yunfu": "云浮",
    "Heyuan": "河源",
    "Shanwei": "汕尾",
    "Luohu District": "罗湖区",
    "Nanshan": "南山",
    "Futian": "福田",
    "Longgang": "龙岗",
    "Baoan": "宝安",
    
    # 江苏省
    "Suzhou": "苏州",
    "Wuxi": "无锡",
    "Xuzhou": "徐州",
    "Changzhou": "常州",
    "Nantong": "南通",
    "Lianyungang": "连云港",
    "Huai'an": "淮安",
    "Huaian": "淮安",
    "Yancheng": "盐城",
    "Yangzhou": "扬州",
    "Zhenjiang": "镇江",
    "Taizhou": "泰州",
    "Suqian": "宿迁",
    "Kunshan": "昆山",
    "Jiangyin": "江阴",
    "Zhangjiagang": "张家港",
    "Changshu": "常熟",
    "Taicang": "太仓",
    "Rugao": "如皋",
    
    # 浙江省
    "Ningbo": "宁波",
    "Wenzhou": "温州",
    "Jiaxing": "嘉兴",
    "Huzhou": "湖州",
    "Shaoxing": "绍兴",
    "Jinhua": "金华",
    "Quzhou": "衢州",
    "Zhoushan": "舟山",
    "Taizhou": "台州",
    "Lishui": "丽水",
    "Yiwu": "义乌",
    "Cixi": "慈溪",
    "Yuyao": "余姚",
    "Yueqing": "乐清",
    "Rui'an": "瑞安",
    
    # 山东省
    "Qingdao": "青岛",
    "Jinan": "济南",
    "Zibo": "淄博",
    "Zaozhuang": "枣庄",
    "Dongying": "东营",
    "Yantai": "烟台",
    "Weifang": "潍坊",
    "Jining": "济宁",
    "Tai'an": "泰安",
    "Taian": "泰安",
    "Weihai": "威海",
    "Rizhao": "日照",
    "Laiwu": "莱芜",
    "Linyi": "临沂",
    "Dezhou": "德州",
    "Liaocheng": "聊城",
    "Binzhou": "滨州",
    "Heze": "菏泽",
    "Gaomi": "高密",
    "Laiyang": "莱阳",
    "Shouguang": "寿光",
    "Zhucheng": "诸城",
    "Zhu Cheng City": "诸城",
    "Tengzhou": "滕州",
    
    # 河南省
    "Luoyang": "洛阳",
    "Kaifeng": "开封",
    "Anyang": "安阳",
    "Xinxiang": "新乡",
    "Pingdingshan": "平顶山",
    "Jiaozuo": "焦作",
    "Hebi": "鹤壁",
    "Puyang": "濮阳",
    "Xuchang": "许昌",
    "Luohe": "漯河",
    "Sanmenxia": "三门峡",
    "Nanyang": "南阳",
    "Shangqiu": "商丘",
    "Xinyang": "信阳",
    "Zhoukou": "周口",
    "Zhumadian": "驻马店",
    
    # 湖北省
    "Huangshi": "黄石",
    "Shiyan": "十堰",
    "Yichang": "宜昌",
    "Xiangyang": "襄阳",
    "Ezhou": "鄂州",
    "Jingmen": "荆门",
    "Xiaogan": "孝感",
    "Jingzhou": "荆州",
    "Huanggang": "黄冈",
    "Xianning": "咸宁",
    "Suizhou": "随州",
    
    # 湖南省
    "Zhuzhou": "株洲",
    "Xiangtan": "湘潭",
    "Hengyang": "衡阳",
    "Shaoyang": "邵阳",
    "Yueyang": "岳阳",
    "Changde": "常德",
    "Zhangjiajie": "张家界",
    "Yiyang": "益阳",
    "Chenzhou": "郴州",
    "Yongzhou": "永州",
    "Huaihua": "怀化",
    "Loudi": "娄底",
    
    # 四川省
    "Zigong": "自贡",
    "Panzhihua": "攀枝花",
    "Luzhou": "泸州",
    "Deyang": "德阳",
    "Mianyang": "绵阳",
    "Guangyuan": "广元",
    "Suining": "遂宁",
    "Neijiang": "内江",
    "Leshan": "乐山",
    "Nanchong": "南充",
    "Meishan": "眉山",
    "Yibin": "宜宾",
    "Guang'an": "广安",
    "Dazhou": "达州",
    "Ya'an": "雅安",
    "Bazhong": "巴中",
    "Ziyang": "资阳",
    
    # 陕西省
    "Baoji": "宝鸡",
    "Xianyang": "咸阳",
    "Weinan": "渭南",
    "Yan'an": "延安",
    "Hanzhong": "汉中",
    "Yulin": "榆林",
    "Ankang": "安康",
    "Shangluo": "商洛",
    
    # 山西省
    "Datong": "大同",
    "Yangquan": "阳泉",
    "Changzhi": "长治",
    "Jincheng": "晋城",
    "Shuozhou": "朔州",
    "Jinzhong": "晋中",
    "Yuncheng": "运城",
    "Xinzhou": "忻州",
    "Linfen": "临汾",
    "Lüliang": "吕梁",
    "Lueliang": "吕梁",
    
    # 河北省
    "Tangshan": "唐山",
    "Qinhuangdao": "秦皇岛",
    "Handan": "邯郸",
    "Xingtai": "邢台",
    "Baoding": "保定",
    "Zhangjiakou": "张家口",
    "Chengde": "承德",
    "Cangzhou": "沧州",
    "Langfang": "廊坊",
    "Hengshui": "衡水",
    
    # 辽宁省
    "Anshan": "鞍山",
    "Fushun": "抚顺",
    "Benxi": "本溪",
    "Dandong": "丹东",
    "Jinzhou": "锦州",
    "Yingkou": "营口",
    "Fuxin": "阜新",
    "Liaoyang": "辽阳",
    "Panjin": "盘锦",
    "Tieling": "铁岭",
    "Chaoyang": "朝阳",
    "Huludao": "葫芦岛",
    "Panshan": "盘山",
    
    # 吉林省
    "Jilin": "吉林",
    "Siping": "四平",
    "Liaoyuan": "辽源",
    "Tonghua": "通化",
    "Baishan": "白山",
    "Songyuan": "松原",
    "Baicheng": "白城",
    "Yanbian": "延边",
    
    # 黑龙江省
    "Qiqihar": "齐齐哈尔",
    "Jixi": "鸡西",
    "Hegang": "鹤岗",
    "Shuangyashan": "双鸭山",
    "Daqing": "大庆",
    "Yichun": "伊春",
    "Jiamusi": "佳木斯",
    "Qitaihe": "七台河",
    "Mudanjiang": "牡丹江",
    "Heihe": "黑河",
    "Suihua": "绥化",
    "Daxing'anling": "大兴安岭",
    
    # 安徽省
    "Wuhu": "芜湖",
    "Bengbu": "蚌埠",
    "Huainan": "淮南",
    "Ma'anshan": "马鞍山",
    "Huaibei": "淮北",
    "Tongling": "铜陵",
    "Anqing": "安庆",
    "Huangshan": "黄山",
    "Chuzhou": "滁州",
    "Fuyang": "阜阳",
    "Suzhou": "宿州",
    "Lu'an": "六安",
    "Bozhou": "亳州",
    "Chizhou": "池州",
    "Xuancheng": "宣城",
    
    # 江西省
    "Jingdezhen": "景德镇",
    "Pingxiang": "萍乡",
    "Jiujiang": "九江",
    "Xinyu": "新余",
    "Yingtan": "鹰潭",
    "Ganzhou": "赣州",
    "Ji'an": "吉安",
    "Yichun": "宜春",
    "Fuzhou": "抚州",
    "Shangrao": "上饶",
    
    # 福建省
    "Quanzhou": "泉州",
    "Zhangzhou": "漳州",
    "Sanming": "三明",
    "Putian": "莆田",
    "Nanping": "南平",
    "Longyan": "龙岩",
    "Ningde": "宁德",
    
    # 重庆区县
    "Wanzhou": "万州",
    "Fuling": "涪陵",
    "Yubei": "渝北",
    "Jiangbei": "江北",
    "Yuzhong": "渝中",
    
    # 上海区县
    "Pudong": "浦东",
    "Minhang": "闵行",
    "Baoshan": "宝山",
    "Jiading": "嘉定",
    "Songjiang": "松江",
    "Qingpu": "青浦",
    "Fengxian": "奉贤",
    "Jinshan": "金山",
    "Zhabei": "闸北",
    "Changning": "长宁",
    "Putuo": "普陀",
    "Hongkou": "虹口",
    "Yangpu": "杨浦",
    
    # 内蒙古
    "Baotou": "包头",
    "Wuhai": "乌海",
    "Chifeng": "赤峰",
    "Tongliao": "通辽",
    "Ordos": "鄂尔多斯",
    "Hulunbuir": "呼伦贝尔",
    "Bayannur": "巴彦淖尔",
    "Bayan Nur": "巴彦淖尔",
    "Ulanqab": "乌兰察布",
    "Hinggan": "兴安盟",
    "Xilingol": "锡林郭勒",
    "Alxa": "阿拉善",
    
    # 宁夏
    "Shizuishan": "石嘴山",
    "Wuzhong": "吴忠",
    "Guyuan": "固原",
    "Zhongwei": "中卫",
    
    # 新疆
    "Karamay": "克拉玛依",
    "Turpan": "吐鲁番",
    "Hami": "哈密",
    "Changji": "昌吉",
    "Bortala": "博尔塔拉",
    "Bayingolin": "巴音郭楞",
    "Aksu": "阿克苏",
    "Kizilsu": "克孜勒苏",
    "Kashgar": "喀什",
    "Hotan": "和田",
    "Ili": "伊犁",
    "Tacheng": "塔城",
    "Altay": "阿勒泰",
    
    # 甘肃
    "Jiayuguan": "嘉峪关",
    "Jinchang": "金昌",
    "Baiyin": "白银",
    "Tianshui": "天水",
    "Wuwei": "武威",
    "Zhangye": "张掖",
    "Pingliang": "平凉",
    "Jiuquan": "酒泉",
    "Qingyang": "庆阳",
    "Dingxi": "定西",
    "Longnan": "陇南",
    "Linxia": "临夏",
    "Gannan": "甘南",
    
    # 青海
    "Haidong": "海东",
    "Haibei": "海北",
    "Huangnan": "黄南",
    "Hainan": "海南",
    "Golog": "果洛",
    "Yushu": "玉树",
    "Haixi": "海西",
    
    # 西藏
    "Qamdo": "昌都",
    "Shannan": "山南",
    "Shigatse": "日喀则",
    "Nagqu": "那曲",
    "Ngari": "阿里",
    "Nyingchi": "林芝",
    "Chéngguān Qū": "城关区",
    "Chengguan Qu": "城关区",
    
    # 云南
    "Qujing": "曲靖",
    "Yuxi": "玉溪",
    "Baoshan": "保山",
    "Zhaotong": "昭通",
    "Lijiang": "丽江",
    "Pu'er": "普洱",
    "Lincang": "临沧",
    "Chuxiong": "楚雄",
    "Honghe": "红河",
    "Mengzi": "蒙自",
    "Wenshan": "文山",
    "Xishuangbanna": "西双版纳",
    "Dali": "大理",
    "Dehong": "德宏",
    "Nujiang": "怒江",
    "Diqing": "迪庆",
    
    # 贵州
    "Liupanshui": "六盘水",
    "Zunyi": "遵义",
    "Anshun": "安顺",
    "Bijie": "毕节",
    "Tongren": "铜仁",
    "Qianxinan": "黔西南",
    "Qiandongnan": "黔东南",
    "Qiannan": "黔南",
    
    # 广西
    "Liuzhou": "柳州",
    "Guilin": "桂林",
    "Wuzhou": "梧州",
    "Beihai": "北海",
    "Fangchenggang": "防城港",
    "Qinzhou": "钦州",
    "Guigang": "贵港",
    "Yulin": "玉林",
    "Baise": "百色",
    "Hezhou": "贺州",
    "Hechi": "河池",
    "Laibin": "来宾",
    "Chongzuo": "崇左",
    
    # 海南
    "Sansha": "三沙",
    "Danzhou": "儋州",
    "Wuzhishan": "五指山",
    "Wenchang": "文昌",
    "Qionghai": "琼海",
    "Wanning": "万宁",
    "Dongfang": "东方",
    "Basuo": "八所",
    
    # 其他常见城市/区县
    "Daxing": "大兴",
    "Tongzhou": "通州",
    "Shunyi": "顺义",
    "Changping": "昌平",
    "Fengtai": "丰台",
    "Haidian": "海淀",
    "Chaoyang": "朝阳",
    "Xicheng": "西城",
    "Dongcheng": "东城",
    "Mentougou": "门头沟",
    "Fangshan": "房山",
    "Daxing": "大兴",
    "Huairou": "怀柔",
    "Pinggu": "平谷",
    "Miyun": "密云",
    "Yanqing": "延庆",
    
    # 天津区县
    "Binhai": "滨海",
    "Hedong": "河东",
    "Hexi": "河西",
    "Nankai": "南开",
    "Hebei": "河北",
    "Hongqiao": "红桥",
    "Dongli": "东丽",
    "Xiqing": "西青",
    "Jinnan": "津南",
    "Beichen": "北辰",
    "Wuqing": "武清",
    "Baodi": "宝坻",
    "Ninghe": "宁河",
    "Jinghai": "静海",
    "Jixian": "蓟县",
    "Ji County": "蓟县",
    
    # 其他地级市
    "Pengpu": "彭浦",
    "Guli": "古里",
    "Jiaozhou": "胶州",
    "Jimo": "即墨",
    "Laixi": "莱西",
    "Pingdu": "平度",
    "Rongcheng": "荣成",
    "Wendeng": "文登",
    "Rushan": "乳山",
    "Longkou": "龙口",
    "Laizhou": "莱州",
    "Zhaoyuan": "招远",
    "Penglai": "蓬莱",
    "Qixia": "栖霞",
    "Haiyang": "海阳",
    "Anqiu": "安丘",
    "Changyi": "昌邑",
    "Gaomi": "高密",
    "Qingzhou": "青州",
    "Zhucheng": "诸城",
    "Shouguang": "寿光",
    "Linqu": "临朐",
    "Changle": "昌乐",
    "Qufu": "曲阜",
    "Yanzhou": "兖州",
    "Zoucheng": "邹城",
    "Weishan": "微山",
    "Yutai": "鱼台",
    "Jinxiang": "金乡",
    "Jiaxiang": "嘉祥",
    "Wenshang": "汶上",
    "Sishui": "泗水",
    "Liangshan": "梁山",
    "Feicheng": "肥城",
    "Xintai": "新泰",
    "Ningyang": "宁阳",
    "Dongping": "东平",
    "Rongcheng": "荣成",
    "Rushan": "乳山",
    "Wendeng": "文登",
    "Laiyang": "莱阳",
    "Laizhou": "莱州",
    "Zhaoyuan": "招远",
    "Longkou": "龙口",
    "Penglai": "蓬莱",
    "Qixia": "栖霞",
    "Haiyang": "海阳",
    
    # 县级市/区
    "Mianzhu, Deyang, Sichuan": "绵竹",
    "Mianzhu": "绵竹",
    "Bei'an": "北安",
    "Beian": "北安",
    "Changshu City": "常熟",
    "Yiwu City": "义乌",
    "Yuyao City": "余姚",
    "Cixi City": "慈溪",
    
    # 更多县级市
    "Fenghuang": "凤凰",
    "Lhoka": "山南",
    "Pengze": "彭泽",
    "Xilinhot": "锡林浩特",
    "Daye": "大冶",
    "Yunlong": "云龙",
    "Pizhou": "邳州",
    "Yangshuo": "阳朔",
    "Artux": "阿图什",
    "Kaili": "凯里",
    "Longling County": "龙陵",
    "Longling": "龙陵",
    "Hulan Ergi": "呼兰",
    "Dongtai": "东台",
    "Nianbo": "碾伯",
    "Suicheng": "遂城",
    "Nada": "纳达",
    "Wafangdian": "瓦房店",
    "Huayin": "华阴",
    "Jiyuan": "济源",
    "Xiantao": "仙桃",
    "Yuci": "榆次",
    "Jingling": "京陵",
    "Wuxue": "武穴",
    "Yintai": "印台",
    "Luojiang": "洛江",
    "Hailar": "海拉尔",
    "Daliang": "大良",
    "Hangu": "汉沽",
    "Beiliu": "北流",
    "Duyun": "都匀",
    "Kaiyuan": "开原",
    "Lushui": "泸水",
    "Zhaodong": "肇东",
    "Acheng": "阿城",
    "Haining": "海宁",
    "Mingguang": "明光",
    "Jiutai": "九台",
    "Zhuji": "诸暨",
    "Qingtongxia": "青铜峡",
    "Yiwu": "义乌",
    "Anda": "安达",
    "Huangyan": "黄岩",
    "Yuhuan": "玉环",
    "Jiaojiang": "椒江",
    "Linhai": "临海",
    "Wenling": "温岭",
    "Sanmen": "三门",
    "Tiantai": "天台",
    "Xianju": "仙居",
    "Jinyun": "缙云",
    "Suichang": "遂昌",
    "Songyang": "松阳",
    "Yunhe": "云和",
    "Qingyuan": "庆元",
    "Jingning": "景宁",
    "Longquan": "龙泉",
    "Pujiang": "浦江",
    "Wuyi": "武义",
    "Pan'an": "磐安",
    "Yongkang": "永康",
    "Dongyang": "东阳",
    "Lanxi": "兰溪",
    "Yiwu": "义乌",
    "Shengzhou": "嵊州",
    "Xinchang": "新昌",
    "Shangyu": "上虞",
    "Zhuji": "诸暨",
    "Shaoxing County": "绍兴县",
    "Tongxiang": "桐乡",
    "Haiyan": "海盐",
    "Pinghu": "平湖",
    "Jiashan": "嘉善",
    "Anji": "安吉",
    "Deqing": "德清",
    "Changxing": "长兴",
    "Qujiang": "曲江",
    "Kaihua": "开化",
    "Changshan": "常山",
    "Jiangshan": "江山",
    "Longyou": "龙游",
    "Pingyang": "平阳",
    "Cangnan": "苍南",
    "Wencheng": "文成",
    "Taishun": "泰顺",
    "Yongjia": "永嘉",
    "Dongtou": "洞头",
    "Ruian": "瑞安",
    "Yueqing": "乐清",
    "Dinghai": "定海",
    "Putuo": "普陀",
    "Daishan": "岱山",
    "Shengsi": "嵊泗",
    "Linping": "临平",
    "Yuhang": "余杭",
    "Fuyang": "富阳",
    "Lin'an": "临安",
    "Jiande": "建德",
    "Tonglu": "桐庐",
    "Chun'an": "淳安",
    
    # 江苏县级市
    "Haimen": "海门",
    "Qidong": "启东",
    "Rugao": "如皋",
    "Tongzhou": "通州",
    "Rudong": "如东",
    "Hai'an": "海安",
    "Dongtai": "东台",
    "Dafeng": "大丰",
    "Jianhu": "建湖",
    "Xiangshui": "响水",
    "Binhai": "滨海",
    "Funing": "阜宁",
    "Sheyang": "射阳",
    "Baoying": "宝应",
    "Gaoyou": "高邮",
    "Yizheng": "仪征",
    "Jiangdu": "江都",
    "Danyang": "丹阳",
    "Yangzhong": "扬中",
    "Jurong": "句容",
    "Jingjiang": "靖江",
    "Taixing": "泰兴",
    "Xinghua": "兴化",
    "Sihong": "泗洪",
    "Shuyang": "沭阳",
    "Siyang": "泗阳",
    "Jintan": "金坛",
    "Liyang": "溧阳",
    "Yixing": "宜兴",
    "Xinyi": "新沂",
    "Pizhou": "邳州",
    "Donghai": "东海",
    "Ganyu": "赣榆",
    "Guanyun": "灌云",
    "Guannan": "灌南",
    "Lianshui": "涟水",
    "Hongze": "洪泽",
    "Xuyi": "盱眙",
    "Jinhu": "金湖",
    
    # 山东县级市
    "Laiyang": "莱阳",
    "Laizhou": "莱州",
    "Penglai": "蓬莱",
    "Zhaoyuan": "招远",
    "Longkou": "龙口",
    "Qixia": "栖霞",
    "Haiyang": "海阳",
    "Rongcheng": "荣成",
    "Wendeng": "文登",
    "Rushan": "乳山",
    "Pingdu": "平度",
    "Jiaonan": "胶南",
    "Jimo": "即墨",
    "Zhucheng": "诸城",
    "Anqiu": "安丘",
    "Changyi": "昌邑",
    "Gaomi": "高密",
    "Qingzhou": "青州",
    "Linqu": "临朐",
    "Changle": "昌乐",
    "Shouguang": "寿光",
    "Qufu": "曲阜",
    "Zoucheng": "邹城",
    "Yanzhou": "兖州",
    "Weishan": "微山",
    "Yutai": "鱼台",
    "Jinxiang": "金乡",
    "Jiaxiang": "嘉祥",
    "Wenshang": "汶上",
    "Sishui": "泗水",
    "Liangshan": "梁山",
    "Feicheng": "肥城",
    "Xintai": "新泰",
    "Ningyang": "宁阳",
    "Dongping": "东平",
    "Tengzhou": "滕州",
    
    # 河南县级市
    "Gongyi": "巩义",
    "Dengzhou": "邓州",
    "Yongcheng": "永城",
    "Xiangcheng": "项城",
    "Jiyuan": "济源",
    "Yima": "义马",
    "Lingbao": "灵宝",
    "Ruzhou": "汝州",
    "Wugang": "舞钢",
    "Linzhou": "林州",
    "Weihui": "卫辉",
    "Huixian": "辉县",
    "Qinyang": "沁阳",
    "Mengzhou": "孟州",
    "Yuzhou": "禹州",
    "Changge": "长葛",
    "Yiyang": "宜阳",
    
    # 湖北县级市
    "Danjiangkou": "丹江口",
    "Laohekou": "老河口",
    "Zaoyang": "枣阳",
    "Yicheng": "宜城",
    "Zhongxiang": "钟祥",
    "Jingshan": "京山",
    "Tianmen": "天门",
    "Qianjiang": "潜江",
    "Xiantao": "仙桃",
    "Chibi": "赤壁",
    "Shishou": "石首",
    "Honghu": "洪湖",
    "Songzi": "松滋",
    "Yidu": "宜都",
    "Dangyang": "当阳",
    "Zhijiang": "枝江",
    "Xiaogan": "孝感",
    "Anlu": "安陆",
    "Hanchuan": "汉川",
    "Macheng": "麻城",
    "Wuxue": "武穴",
    "Guangshui": "广水",
    "Enshi": "恩施",
    "Lichuan": "利川",
    
    # 湖南县级市
    "Leiyang": "耒阳",
    "Changning": "常宁",
    "Liuyang": "浏阳",
    "Liling": "醴陵",
    "Xiangxiang": "湘乡",
    "Shaoshan": "韶山",
    "Wugang": "武冈",
    "Miluo": "汨罗",
    "Linxiang": "临湘",
    "Jinshi": "津市",
    "Lixian": "澧县",
    "Zixing": "资兴",
    "Hongjiang": "洪江",
    "Lengshuijiang": "冷水江",
    "Lianyuan": "涟源",
    "Jishou": "吉首",
    
    # 四川县级市
    "Guanghan": "广汉",
    "Shifang": "什邡",
    "Mianzhu": "绵竹",
    "Jiangyou": "江油",
    "Emeishan": "峨眉山",
    "Langzhong": "阆中",
    "Huaying": "华蓥",
    "Wanyuan": "万源",
    "Jianyang": "简阳",
    "Xichang": "西昌",
    "Kangding": "康定",
    
    # 陕西县级市
    "Xingping": "兴平",
    "Hancheng": "韩城",
    "Huayin": "华阴",
    
    # 山西县级市
    "Gujiao": "古交",
    "Yuci": "榆次",
    "Jiexiu": "介休",
    "Fenyang": "汾阳",
    "Xiaoyi": "孝义",
    "Yongji": "永济",
    "Hejin": "河津",
    "Gaoping": "高平",
    "Huozhou": "霍州",
    "Yuanping": "原平",
    
    # 河北县级市
    "Xinji": "辛集",
    "Gaobeidian": "高碑店",
    "Zhuozhou": "涿州",
    "Dingzhou": "定州",
    "Anguo": "安国",
    "Huanghua": "黄骅",
    "Renqiu": "任丘",
    "Hejian": "河间",
    "Botou": "泊头",
    "Nangong": "南宫",
    "Shahe": "沙河",
    "Wu'an": "武安",
    "Qian'an": "迁安",
    "Zunhua": "遵化",
    "Sanhe": "三河",
    "Xianghe": "香河",
    "Bazhou": "霸州",
    
    # 辽宁县级市
    "Xinmin": "新民",
    "Wafangdian": "瓦房店",
    "Pulandian": "普兰店",
    "Zhuanghe": "庄河",
    "Haicheng": "海城",
    "Dengta": "灯塔",
    "Tieling County": "铁岭县",
    "Kaiyuan": "开原",
    "Beipiao": "北票",
    "Linghai": "凌海",
    "Xingcheng": "兴城",
    "Dashiqiao": "大石桥",
    "Gaizhou": "盖州",
    "Dengta": "灯塔",
    "Diaobingshan": "调兵山",
    "Lingyuan": "凌源",
    "Beizhen": "北镇",
    
    # 吉林县级市
    "Meihekou": "梅河口",
    "Shulan": "舒兰",
    "Panshi": "磐石",
    "Gongzhuling": "公主岭",
    "Shuangliao": "双辽",
    "Meihekou": "梅河口",
    "Ji'an": "集安",
    "Linjiang": "临江",
    "Taonan": "洮南",
    "Daan": "大安",
    "Yanji": "延吉",
    "Tumen": "图们",
    "Dunhua": "敦化",
    "Hunchun": "珲春",
    "Longjing": "龙井",
    "Helong": "和龙",
    "Antu": "安图",
    "Wangqing": "汪清",
    
    # 黑龙江县级市
    "Shangzhi": "尚志",
    "Wuchang": "五常",
    "Shuangcheng": "双城",
    "Nehe": "讷河",
    "Fujin": "富锦",
    "Tongjiang": "同江",
    "Hulin": "虎林",
    "Mishan": "密山",
    "Tieli": "铁力",
    "Suifenhe": "绥芬河",
    "Hailin": "海林",
    "Ning'an": "宁安",
    "Muling": "穆棱",
    "Dongning": "东宁",
    "Linkou": "林口",
    "Suiling": "绥棱",
    "Qing'an": "庆安",
    "Mingshui": "明水",
    "Wangkui": "望奎",
    "Lanxi": "兰西",
    "Qinggang": "青冈",
    "Anda": "安达",
    "Zhaodong": "肇东",
    "Hailun": "海伦",
    "Bei'an": "北安",
    
    # 安徽县级市
    "Tianchang": "天长",
    "Mingguang": "明光",
    "Jieshou": "界首",
    "Tongcheng": "桐城",
    "Qianshan": "潜山",
    "Huaining": "怀宁",
    "Susong": "宿松",
    "Wangjiang": "望江",
    "Yuexi": "岳西",
    "Taihu": "太湖",
    "Langxi": "郎溪",
    "Guangde": "广德",
    "Jing County": "泾县",
    "Jixi": "绩溪",
    "Shexian": "歙县",
    "Xiuning": "休宁",
    "Yixian": "黟县",
    "Qimen": "祁门",
    
    # 江西县级市
    "Leping": "乐平",
    "Ruichang": "瑞昌",
    "Gongqingcheng": "共青城",
    "Lushan": "庐山",
    "Dexing": "德兴",
    "Guixi": "贵溪",
    "Ruijin": "瑞金",
    "Nankang": "南康",
    "Jinggangshan": "井冈山",
    "Fengcheng": "丰城",
    "Zhangshu": "樟树",
    "Gaoan": "高安",
    
    # 福建县级市
    "Fuqing": "福清",
    "Changle": "长乐",
    "Minhou": "闽侯",
    "Lianjiang": "连江",
    "Luoyuan": "罗源",
    "Minqing": "闽清",
    "Yongtai": "永泰",
    "Pingtan": "平潭",
    "Fuding": "福鼎",
    "Fu'an": "福安",
    "Xiapu": "霞浦",
    "Gutian": "古田",
    "Pingnan": "屏南",
    "Shouning": "寿宁",
    "Zhouning": "周宁",
    "Zherong": "柘荣",
    "Shishi": "石狮",
    "Jinjiang": "晋江",
    "Nan'an": "南安",
    "Hui'an": "惠安",
    "Anxi": "安溪",
    "Yongchun": "永春",
    "Dehua": "德化",
    "Kinmen": "金门",
    "Longhai": "龙海",
    "Zhangpu": "漳浦",
    "Yunxiao": "云霄",
    "Dongshan": "东山",
    "Zhao'an": "诏安",
    "Nanjing": "南靖",
    "Pinghe": "平和",
    "Hua'an": "华安",
    "Changtai": "长泰",
    "Jian'ou": "建瓯",
    "Shaowu": "邵武",
    "Wuyishan": "武夷山",
    "Jianyang": "建阳",
    "Songxi": "松溪",
    "Zhenghe": "政和",
    "Pucheng": "浦城",
    "Guangze": "光泽",
    "Shunchang": "顺昌",
    "Yong'an": "永安",
    "Mingxi": "明溪",
    "Qingliu": "清流",
    "Ninghua": "宁化",
    "Datian": "大田",
    "Youxi": "尤溪",
    "Sha County": "沙县",
    "Jiangle": "将乐",
    "Taining": "泰宁",
    "Jianning": "建宁",
    "Zhangping": "漳平",
    
    # 广东更多城市
    "Humen": "虎门",
    "Yangchun": "阳春",
    "Boluo": "博罗",
    "Huicheng": "惠城",
    "Huiyang": "惠阳",
    "Huidong": "惠东",
    "Longmen": "龙门",
    "Enping": "恩平",
    "Kaiping": "开平",
    "Heshan": "鹤山",
    "Taishan": "台山",
    "Nanxiong": "南雄",
    "Lechang": "乐昌",
    "Renhua": "仁化",
    "Shixing": "始兴",
    "Wujiang": "吴江",
    
    # 更多未匹配城市
    "Peicheng": "沛城",
    "Shangri-La": "香格里拉",
    "Ulanhot": "乌兰浩特",
    "Songcheng": "松城",
    "Zhicheng": "枝城",
    "Lianghu": "梁湖",
    "Boshan": "博山",
    "Sujiatun": "苏家屯",
    "Huadian": "桦甸",
    "Fuyu": "扶余",
    "Huinong": "惠农",
    "Jiagedaqi": "加格达奇",
    "Jiawang": "贾汪",
    "Puqi": "蒲圻",
    "Dawukou": "大武口",
    "Wuda": "乌达",
    "Shache": "莎车",
    "Jingzhi": "景芝",
    "Xiazhen": "夏镇",
    "Lecheng": "乐城",
    "Jiupu": "九圃",
    "Huangzhou": "黄州",
    "Xiulin": "秀林",
    "Liulin": "柳林",
    "Zhucun": "朱村",
    "Acheng": "阿城",
    "Zhaodong": "肇东",
    "Shuangyashan": "双鸭山",
    "Qitaihe": "七台河",
    "Mudanjiang": "牡丹江",
    "Hegang": "鹤岗",
    "Jixi": "鸡西",
    "Yichun": "伊春",
    "Heihe": "黑河",
    "Suihua": "绥化",
    "Qiqihar": "齐齐哈尔",
    "Daqing": "大庆",
    "Jiamusi": "佳木斯",
    
    # 人口>10万的24个未匹配城市（手工补充）
    "Zhenping Chengguanzhen": "镇平城关镇",
    "Pingwu County": "平武县",
    "Pingwu": "平武",
    "Xindi": "新堤",
    "Zhoucun": "周村",
    "Xilin Hot": "锡林浩特",
    "Yakeshi": "牙克石",
    "Anliu": "安流",
    "Wayaobu": "瓦窑堡",
    "Maba": "马坝",
    "Datun": "大屯",
    "Linshui": "邻水",
    "Shilong": "石龙",
    "Jianchang": "建昌",
    "Dehui": "德惠",
    "Xuyong": "叙永",
    "Jalai Nur": "扎赉诺尔",
    "Anning": "安宁",
    "Buhe": "布和",
    "Wuchuan": "吴川",
    "Salaqi": "萨拉齐",
    "Jishu": "吉舒",
    "Bashan": "巴山",
    "Huacheng": "花城",
    "Xinzhai": "新寨",
    
    # 更多地级市
    "Pu'er": "普洱",
    "Dehong": "德宏",
    "Nujiang": "怒江",
    "Diqing": "迪庆",
    "Chuxiong": "楚雄",
    "Honghe": "红河",
    "Wenshan": "文山",
    "Xishuangbanna": "西双版纳",
    "Zhaotong": "昭通",
    "Qujing": "曲靖",
    "Yuxi": "玉溪",
    "Lijiang": "丽江",
    
    # 更多县级市和区县
    "Haining": "海宁",
    "Tongxiang": "桐乡",
    "Pinghu": "平湖",
    "Haiyan": "海盐",
    "Jiashan": "嘉善",
    "Anji": "安吉",
    "Deqing": "德清",
    "Changxing": "长兴",
    "Zhuji": "诸暨",
    "Shangyu": "上虞",
    "Shengzhou": "嵊州",
    "Xinchang": "新昌",
    "Dongyang": "东阳",
    "Yongkang": "永康",
    "Lanxi": "兰溪",
    "Pujiang": "浦江",
    "Wuyi": "武义",
    "Pan'an": "磐安",
    "Linhai": "临海",
    "Wenling": "温岭",
    "Yuhuan": "玉环",
    "Jiaojiang": "椒江",
    "Huangyan": "黄岩",
    "Luqiao": "路桥",
    "Sanmen": "三门",
    "Tiantai": "天台",
    "Xianju": "仙居",
    "Jinyun": "缙云",
    "Qingtian": "青田",
    "Suichang": "遂昌",
    "Songyang": "松阳",
    "Yunhe": "云和",
    "Qingyuan": "庆元",
    "Jingning": "景宁",
    "Longquan": "龙泉",
    "Jiangshan": "江山",
    "Longyou": "龙游",
    "Changshan": "常山",
    "Kaihua": "开化",
    "Qujiang": "衢江",
    "Pingyang": "平阳",
    "Cangnan": "苍南",
    "Wencheng": "文成",
    "Taishun": "泰顺",
    "Yongjia": "永嘉",
    "Dongtou": "洞头",
    "Ruian": "瑞安",
    "Yueqing": "乐清",
    "Dinghai": "定海",
    "Daishan": "岱山",
    "Shengsi": "嵊泗",
    "Yuhang": "余杭",
    "Fuyang": "富阳",
    "Lin'an": "临安",
    "Jiande": "建德",
    "Tonglu": "桐庐",
    "Chun'an": "淳安",
    "Linping": "临平",
    "Xiaoshan": "萧山",
    
    # 特殊地名
    "Inner Mongolia": "内蒙古",
    "Xinjiang": "新疆",
    "Tibet": "西藏",
    "Ningxia": "宁夏",
    "Guangxi": "广西",
    "Hong Kong": "香港",
    "Macau": "澳门",
    "Macao": "澳门",
}

def get_chinese_name(english_name: str, ascii_name: str = None) -> str:
    """
    根据英文名或ASCII名获取中文名称
    """
    # 先尝试完全匹配
    if english_name in CITY_NAME_MAPPING:
        return CITY_NAME_MAPPING[english_name]
    
    if ascii_name and ascii_name in CITY_NAME_MAPPING:
        return CITY_NAME_MAPPING[ascii_name]
    
    # 尝试去掉后缀
    for suffix in [" City", " County", " District", " Qu", " Xian", " Shi"]:
        if english_name.endswith(suffix):
            base_name = english_name[:-len(suffix)].strip()
            if base_name in CITY_NAME_MAPPING:
                return CITY_NAME_MAPPING[base_name]
    
    # 尝试部分匹配
    for key, value in CITY_NAME_MAPPING.items():
        if key in english_name or english_name in key:
            return value
    
    return None


def main():
    """主函数：读取TSV，补充中文名称，生成CSV供检验"""
    import csv
    
    input_file = 'cities_no_chinese.tsv'
    output_file = 'cities_chinese_supplement.csv'
    
    print(f'读取文件: {input_file}')
    
    cities = []
    matched = 0
    unmatched = 0
    
    with open(input_file, 'r', encoding='utf-8') as f:
        # 跳过表头
        header = f.readline().strip().split('\t')
        
        for line in f:
            parts = line.strip().split('\t')
            if len(parts) < 4:
                continue
            
            geoname_id = parts[0]
            name = parts[1]
            ascii_name = parts[2] if len(parts) > 2 else None
            population = parts[3] if len(parts) > 3 else 0
            
            # 尝试获取中文名称
            chinese_name = get_chinese_name(name, ascii_name)
            
            if chinese_name:
                matched += 1
                status = '✓'
            else:
                unmatched += 1
                chinese_name = ''  # 留空待人工补充
                status = '✗'
            
            cities.append({
                'geoname_id': geoname_id,
                'name': name,
                'ascii_name': ascii_name or '',
                'name_zh': chinese_name,
                'population': population,
                'status': status
            })
    
    print(f'总共: {len(cities)} 个城市')
    print(f'已匹配: {matched} 个')
    print(f'未匹配: {unmatched} 个')
    print(f'匹配率: {matched * 100.0 / len(cities):.2f}%')
    
    # 写入CSV文件
    print(f'\n生成文件: {output_file}')
    with open(output_file, 'w', encoding='utf-8-sig', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=['status', 'geoname_id', 'name', 'ascii_name', 'name_zh', 'population'])
        writer.writeheader()
        writer.writerows(cities)
    
    print(f'✓ 文件已生成，请检查 {output_file}')
    print(f'✓ 已自动匹配的城市标记为 ✓')
    print(f'✓ 未匹配的城市标记为 ✗，name_zh列为空，需要人工补充')
    print(f'\n请检查并补充 name_zh 列的中文名称，确认无误后运行导入脚本')


if __name__ == '__main__':
    main()

